import Foundation

/// Raw exercise data tuple: (id, name, bodyPart, category, isTimed, isUnilateral, primaryMuscles, secondaryMuscles)
public typealias _Ex = (String, String, String, String, Bool, Bool, [String], [String])

/// All exercises from the React constants. Call `makeExerciseModels()` to create ExerciseM models.
public let allSeedExercises: [_Ex] = [
    ("ex-1", "Bench Press", "Chest", "Barbell", false, false,
     [Muscle.pectorals, Muscle.frontDelts], [Muscle.triceps, Muscle.serratusAnterior]),
    ("ex-11", "Dumbbell Fly", "Chest", "Dumbbell", false, false,
     [Muscle.pectorals], [Muscle.frontDelts, Muscle.biceps]),
    ("ex-12", "Incline Dumbbell Press", "Chest", "Dumbbell", false, false,
     [Muscle.upperChest, Muscle.frontDelts], [Muscle.triceps]),
    ("ex-21", "Cable Crossover", "Chest", "Cable", false, false,
     [Muscle.pectorals, Muscle.lowerChest], [Muscle.frontDelts, Muscle.biceps]),
    ("ex-22", "Decline Bench Press", "Chest", "Barbell", false, false,
     [Muscle.lowerChest, Muscle.pectorals], [Muscle.triceps, Muscle.frontDelts]),
    ("ex-23", "Push-Up", "Chest", "Bodyweight", false, false,
     [Muscle.pectorals, Muscle.frontDelts], [Muscle.triceps, Muscle.abs, Muscle.serratusAnterior]),
    ("ex-24", "Dips", "Chest", "Assisted Bodyweight", false, false,
     [Muscle.lowerChest, Muscle.triceps], [Muscle.frontDelts, Muscle.pectorals]),
    ("ex-25", "Incline Bench Press", "Chest", "Barbell", false, false,
     [Muscle.upperChest, Muscle.frontDelts], [Muscle.triceps]),
    ("ex-26", "Pec Deck Fly", "Chest", "Machine", false, false,
     [Muscle.pectorals], [Muscle.frontDelts]),
    ("ex-27", "Svend Press", "Chest", "Reps Only", false, false,
     [Muscle.pectorals], [Muscle.frontDelts, Muscle.triceps]),
    ("ex-28", "Landmine Press", "Chest", "Barbell", false, true,
     [Muscle.upperChest, Muscle.frontDelts], [Muscle.triceps, Muscle.serratusAnterior]),
    ("ex-29", "Deficit Push-Up", "Chest", "Bodyweight", false, false,
     [Muscle.pectorals], [Muscle.triceps, Muscle.frontDelts]),
    ("ex-30", "Archer Push-Up", "Chest", "Bodyweight", false, true,
     [Muscle.pectorals, Muscle.triceps], [Muscle.frontDelts, Muscle.abs]),
    ("ex-31", "Machine Chest Press", "Chest", "Machine", false, false,
     [Muscle.pectorals], [Muscle.triceps, Muscle.frontDelts]),
    ("ex-32", "Low-to-High Cable Fly", "Chest", "Cable", false, false,
     [Muscle.upperChest], [Muscle.frontDelts, Muscle.biceps]),
    ("ex-33", "High-to-Low Cable Fly", "Chest", "Cable", false, false,
     [Muscle.lowerChest], [Muscle.frontDelts, Muscle.biceps]),
    ("ex-34", "Plate Press", "Chest", "Reps Only", false, false,
     [Muscle.pectorals], [Muscle.frontDelts, Muscle.triceps]),
    ("ex-35", "Suspension Push-Up", "Chest", "Assisted Bodyweight", false, false,
     [Muscle.pectorals, Muscle.abs], [Muscle.triceps, Muscle.frontDelts, Muscle.serratusAnterior]),
    ("ex-36", "Isometric Chest Squeeze", "Chest", "Bodyweight", true, false,
     [Muscle.pectorals], []),
    ("ex-37", "Speed Bench Press", "Chest", "Barbell", false, false,
     [Muscle.pectorals, Muscle.triceps], [Muscle.frontDelts]),
    ("ex-5", "Barbell Row", "Back", "Barbell", false, false,
     [Muscle.lats, Muscle.rhomboids, Muscle.traps], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rearDelts, Muscle.lowerBack]),
    ("ex-10", "Lat Pulldown", "Back", "Cable", false, false,
     [Muscle.lats], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.teresMajor]),
    ("ex-3", "Deadlift", "Back", "Barbell", false, false,
     [Muscle.lowerBack, Muscle.hamstrings, Muscle.glutes, Muscle.traps], [Muscle.lats, Muscle.forearms, Muscle.wristFlexors, Muscle.quads, Muscle.abs]),
    ("ex-6", "Pull Up", "Back", "Assisted Bodyweight", false, false,
     [Muscle.lats, Muscle.teresMajor], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rhomboids, Muscle.traps]),
    ("ex-38", "Seated Row", "Back", "Cable", false, false,
     [Muscle.lats, Muscle.rhomboids, Muscle.traps], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rearDelts]),
    ("ex-39", "T-Bar Row", "Back", "Machine", false, false,
     [Muscle.lats, Muscle.traps, Muscle.rhomboids], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.lowerBack]),
    ("ex-40", "Single-Arm Dumbbell Row", "Back", "Dumbbell", false, true,
     [Muscle.lats], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rhomboids, Muscle.rearDelts]),
    ("ex-41", "Face Pull", "Back", "Cable", false, false,
     [Muscle.rearDelts, Muscle.rotatorCuff, Muscle.traps], [Muscle.rhomboids, Muscle.biceps, Muscle.forearms]),
    ("ex-42", "Inverted Row", "Back", "Bodyweight", false, false,
     [Muscle.lats, Muscle.rhomboids], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rearDelts, Muscle.abs]),
    ("ex-43", "Rack Pull", "Back", "Barbell", false, false,
     [Muscle.traps, Muscle.lowerBack], [Muscle.lats, Muscle.glutes, Muscle.hamstrings, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-44", "Straight-Arm Pulldown", "Back", "Cable", false, false,
     [Muscle.lats, Muscle.teresMajor], [Muscle.triceps, Muscle.abs, Muscle.serratusAnterior]),
    ("ex-45", "Hyperextension", "Back", "Bodyweight", false, false,
     [Muscle.lowerBack], [Muscle.glutes, Muscle.hamstrings, Muscle.spinalErectors]),
    ("ex-46", "Superman", "Back", "Bodyweight", false, false,
     [Muscle.lowerBack], [Muscle.glutes, Muscle.spinalErectors]),
    ("ex-47", "Renegade Row", "Back", "Dumbbell", false, true,
     [Muscle.lats, Muscle.abs], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.frontDelts, Muscle.obliques]),
    ("ex-48", "Meadows Row", "Back", "Barbell", false, true,
     [Muscle.lats, Muscle.rhomboids], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rearDelts]),
    ("ex-49", "Cable Pull-Over", "Back", "Cable", false, false,
     [Muscle.lats], [Muscle.triceps, Muscle.serratusAnterior, Muscle.abs]),
    ("ex-50", "Chin-Up", "Back", "Assisted Bodyweight", false, false,
     [Muscle.lats, Muscle.biceps], [Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rhomboids]),
    ("ex-51", "Shrugs", "Back", "Dumbbell", false, false,
     [Muscle.traps], [Muscle.forearms, Muscle.wristFlexors]),
    ("ex-52", "Reverse Grip Pulldown", "Back", "Cable", false, false,
     [Muscle.lats, Muscle.biceps], [Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors, Muscle.rhomboids]),
    ("ex-53", "Band Pull-Apart", "Back", "Reps Only", false, false,
     [Muscle.rearDelts, Muscle.rhomboids], [Muscle.traps]),
    ("ex-54", "Farmer's Carry", "Back", "Dumbbell", true, false,
     [Muscle.traps, Muscle.forearms, Muscle.wristFlexors], [Muscle.abs, Muscle.obliques, Muscle.glutes, Muscle.quads, Muscle.hamstrings]),
    ("ex-55", "Good Morning", "Back", "Barbell", false, false,
     [Muscle.lowerBack, Muscle.hamstrings, Muscle.glutes], [Muscle.abs, Muscle.spinalErectors]),
    ("ex-148", "Kettlebell High Pull", "Back", "Kettlebell", false, true,
     [Muscle.traps, Muscle.rearDelts], [Muscle.lats, Muscle.biceps, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-4", "Overhead Press", "Shoulders", "Barbell", false, false,
     [Muscle.frontDelts, Muscle.sideDelts], [Muscle.triceps, Muscle.upperChest, Muscle.serratusAnterior, Muscle.traps]),
    ("ex-56", "Lateral Raise", "Shoulders", "Dumbbell", false, false,
     [Muscle.sideDelts], [Muscle.traps, Muscle.forearms]),
    ("ex-57", "Front Raise", "Shoulders", "Dumbbell", false, false,
     [Muscle.frontDelts], [Muscle.upperChest, Muscle.forearms]),
    ("ex-58", "Rear Delt Fly", "Shoulders", "Dumbbell", false, false,
     [Muscle.rearDelts], [Muscle.rhomboids, Muscle.traps, Muscle.forearms]),
    ("ex-59", "Upright Row", "Shoulders", "Barbell", false, false,
     [Muscle.sideDelts, Muscle.traps], [Muscle.biceps, Muscle.brachialis, Muscle.forearms, Muscle.frontDelts, Muscle.wristFlexors]),
    ("ex-60", "Arnold Press", "Shoulders", "Dumbbell", false, false,
     [Muscle.frontDelts, Muscle.sideDelts], [Muscle.triceps, Muscle.traps]),
    ("ex-61", "Cable Lateral Raise", "Shoulders", "Cable", false, true,
     [Muscle.sideDelts], [Muscle.forearms]),
    ("ex-62", "Pike Push-Up", "Shoulders", "Bodyweight", false, false,
     [Muscle.frontDelts], [Muscle.triceps, Muscle.upperChest, Muscle.serratusAnterior, Muscle.traps]),
    ("ex-63", "Handstand Push-Up", "Shoulders", "Bodyweight", false, false,
     [Muscle.frontDelts, Muscle.triceps], [Muscle.sideDelts, Muscle.serratusAnterior, Muscle.traps]),
    ("ex-64", "Egyptian Lateral Raise", "Shoulders", "Dumbbell", false, true,
     [Muscle.sideDelts], [Muscle.forearms]),
    ("ex-65", "Y-Raise", "Shoulders", "Dumbbell", false, false,
     [Muscle.sideDelts, Muscle.traps], [Muscle.rearDelts, Muscle.forearms]),
    ("ex-66", "Cuban Press", "Shoulders", "Dumbbell", false, false,
     [Muscle.rotatorCuff, Muscle.sideDelts], [Muscle.traps, Muscle.forearms]),
    ("ex-67", "Machine Shoulder Press", "Shoulders", "Machine", false, false,
     [Muscle.frontDelts], [Muscle.triceps, Muscle.sideDelts]),
    ("ex-68", "Behind-the-Neck Press", "Shoulders", "Barbell", false, false,
     [Muscle.sideDelts, Muscle.frontDelts], [Muscle.triceps, Muscle.traps]),
    ("ex-69", "Plate Front Raise", "Shoulders", "Reps Only", false, false,
     [Muscle.frontDelts], [Muscle.forearms, Muscle.wristFlexors]),
    ("ex-70", "Band Shoulder Press", "Shoulders", "Reps Only", false, false,
     [Muscle.frontDelts], [Muscle.triceps]),
    ("ex-71", "Dumbbell Shrugs", "Shoulders", "Dumbbell", false, false,
     [Muscle.traps], [Muscle.forearms, Muscle.wristFlexors]),
    ("ex-72", "Wall Slide", "Shoulders", "Bodyweight", false, false,
     [Muscle.rotatorCuff, Muscle.serratusAnterior], [Muscle.traps]),
    ("ex-7", "Barbell Curl", "Biceps", "Barbell", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.brachialis, Muscle.wristFlexors]),
    ("ex-13", "Bicep Curl", "Biceps", "Dumbbell", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.brachialis, Muscle.wristFlexors]),
    ("ex-73", "Hammer Curl", "Biceps", "Dumbbell", false, false,
     [Muscle.brachialis, Muscle.forearms], [Muscle.biceps, Muscle.wristExtensors]),
    ("ex-74", "Concentration Curl", "Biceps", "Dumbbell", false, true,
     [Muscle.biceps], [Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-75", "Preacher Curl", "Biceps", "Machine", false, false,
     [Muscle.biceps], [Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-76", "Cable Curl", "Biceps", "Cable", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.brachialis, Muscle.wristFlexors]),
    ("ex-77", "Incline Dumbbell Curl", "Biceps", "Dumbbell", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.wristFlexors]),
    ("ex-78", "21s Curl", "Biceps", "Barbell", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.brachialis, Muscle.wristFlexors]),
    ("ex-79", "Spider Curl", "Biceps", "Barbell", false, false,
     [Muscle.biceps], [Muscle.brachialis, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-80", "Zottman Curl", "Biceps", "Dumbbell", false, false,
     [Muscle.biceps, Muscle.forearms], [Muscle.brachialis, Muscle.wristExtensors, Muscle.wristFlexors]),
    ("ex-81", "Bayesian Cable Curl", "Biceps", "Cable", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.wristFlexors]),
    ("ex-82", "Isometric Bicep Hold", "Biceps", "Bodyweight", false, false,
     [Muscle.biceps], [Muscle.forearms, Muscle.wristFlexors]),
    ("ex-83", "Band Curl", "Biceps", "Reps Only", false, false,
     [Muscle.biceps], [Muscle.forearms]),
    ("ex-84", "Drag Curl", "Biceps", "Barbell", false, false,
     [Muscle.biceps], [Muscle.rearDelts, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-8", "Skull Crusher", "Triceps", "Barbell", false, false,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-14", "Tricep Extension", "Triceps", "Cable", false, false,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-85", "Tricep Pushdown", "Triceps", "Cable", false, false,
     [Muscle.triceps], [Muscle.abs, Muscle.forearms]),
    ("ex-86", "Overhead Tricep Extension", "Triceps", "Dumbbell", false, false,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-87", "Close-Grip Bench Press", "Triceps", "Barbell", false, false,
     [Muscle.triceps], [Muscle.pectorals, Muscle.frontDelts]),
    ("ex-88", "French Press", "Triceps", "Barbell", false, false,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-89", "Bench Dip", "Triceps", "Bodyweight", false, false,
     [Muscle.triceps], [Muscle.frontDelts, Muscle.pectorals]),
    ("ex-90", "Rope Pushdown", "Triceps", "Cable", false, false,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-91", "JM Press", "Triceps", "Barbell", false, false,
     [Muscle.triceps], [Muscle.pectorals, Muscle.frontDelts, Muscle.forearms]),
    ("ex-92", "Kickback", "Triceps", "Dumbbell", false, true,
     [Muscle.triceps], [Muscle.rearDelts]),
    ("ex-93", "Reverse Grip Pushdown", "Triceps", "Cable", false, false,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-94", "Cross-Body Extension", "Triceps", "Dumbbell", false, true,
     [Muscle.triceps], [Muscle.forearms]),
    ("ex-95", "Band Pushdown", "Triceps", "Reps Only", false, false,
     [Muscle.triceps], []),
    ("ex-96", "Partial Tricep Extension", "Triceps", "Cable", false, false,
     [Muscle.triceps], []),
    ("ex-97", "Isometric Tricep Squeeze", "Triceps", "Bodyweight", false, false,
     [Muscle.triceps], []),
    ("ex-139", "Wrist Curl", "Forearms", "Dumbbell", false, false,
     [Muscle.wristFlexors], [Muscle.forearms]),
    ("ex-140", "Reverse Wrist Curl", "Forearms", "Dumbbell", false, false,
     [Muscle.wristExtensors], [Muscle.forearms]),
    ("ex-16", "Leg Curl", "Legs", "Machine", false, false,
     [Muscle.hamstrings], [Muscle.calves]),
    ("ex-17", "Leg Extension", "Legs", "Machine", false, false,
     [Muscle.quads], []),
    ("ex-9", "Leg Press", "Legs", "Machine", false, false,
     [Muscle.quads, Muscle.glutes], [Muscle.hamstrings, Muscle.calves]),
    ("ex-2", "Barbell Squat", "Legs", "Barbell", false, false,
     [Muscle.quads, Muscle.glutes], [Muscle.hamstrings, Muscle.lowerBack, Muscle.adductors, Muscle.abs, Muscle.spinalErectors]),
    ("ex-98", "Romanian Deadlift", "Legs", "Barbell", false, false,
     [Muscle.hamstrings, Muscle.glutes], [Muscle.lowerBack, Muscle.forearms, Muscle.wristFlexors, Muscle.adductors]),
    ("ex-99", "Dumbbell Walking Lunge", "Legs", "Dumbbell", false, true,
     [Muscle.quads, Muscle.glutes], [Muscle.hamstrings, Muscle.calves, Muscle.adductors, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-100", "Bulgarian Split Squat", "Legs", "Dumbbell", false, true,
     [Muscle.quads, Muscle.glutes], [Muscle.hamstrings, Muscle.adductors, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-101", "Front Squat", "Legs", "Barbell", false, false,
     [Muscle.quads], [Muscle.glutes, Muscle.lowerBack, Muscle.abs, Muscle.traps, Muscle.rhomboids]),
    ("ex-102", "Hack Squat", "Legs", "Machine", false, false,
     [Muscle.quads], [Muscle.glutes, Muscle.calves]),
    ("ex-103", "Dumbbell Step-Up", "Legs", "Dumbbell", false, true,
     [Muscle.quads, Muscle.glutes], [Muscle.calves, Muscle.hamstrings, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-108", "Sumo Squat", "Legs", "Dumbbell", false, false,
     [Muscle.quads, Muscle.adductors, Muscle.glutes], [Muscle.hamstrings, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-109", "Goblet Squat", "Legs", "Dumbbell", false, false,
     [Muscle.quads, Muscle.glutes], [Muscle.abs, Muscle.traps, Muscle.forearms, Muscle.biceps]),
    ("ex-110", "Pistol Squat", "Legs", "Bodyweight", false, true,
     [Muscle.quads, Muscle.glutes], [Muscle.calves, Muscle.abs]),
    ("ex-111", "Wall Sit", "Legs", "Bodyweight", true, false,
     [Muscle.quads], [Muscle.calves]),
    ("ex-112", "Sissy Squat", "Legs", "Bodyweight", false, false,
     [Muscle.quads], [Muscle.abs]),
    ("ex-113", "Jefferson Squat", "Legs", "Barbell", false, false,
     [Muscle.quads, Muscle.glutes, Muscle.adductors], [Muscle.hamstrings, Muscle.forearms, Muscle.wristFlexors]),
    ("ex-114", "Band Leg Curl", "Legs", "Reps Only", false, true,
     [Muscle.hamstrings], []),
    ("ex-116", "Box Jump", "Legs", "Plyometrics", false, false,
     [Muscle.quads, Muscle.glutes, Muscle.calves], [Muscle.hamstrings]),
    ("ex-150", "Broad Jump", "Legs", "Plyometrics", false, false,
     [Muscle.quads, Muscle.glutes, Muscle.hamstrings], [Muscle.calves]),
    ("ex-151", "Tuck Jump", "Legs", "Plyometrics", false, false,
     [Muscle.quads, Muscle.calves], [Muscle.abs]),
    ("ex-152", "Depth Jump", "Legs", "Plyometrics", false, false,
     [Muscle.quads, Muscle.glutes, Muscle.calves], []),
    ("ex-160", "Squat", "Legs", "Bodyweight", false, false,
     [Muscle.quads, Muscle.glutes], [Muscle.hamstrings]),
    ("ex-161", "Step-Up", "Legs", "Bodyweight", false, true,
     [Muscle.quads, Muscle.glutes], [Muscle.calves]),
    ("ex-162", "Lunge", "Legs", "Bodyweight", false, true,
     [Muscle.quads, Muscle.glutes], [Muscle.hamstrings]),
    ("ex-104", "Glute Bridge", "Glutes", "Bodyweight", false, false,
     [Muscle.glutes], [Muscle.hamstrings]),
    ("ex-141", "Barbell Hip Thrust", "Glutes", "Barbell", false, false,
     [Muscle.glutes], [Muscle.hamstrings, Muscle.quads]),
    ("ex-142", "Glute Kickback", "Glutes", "Cable", false, true,
     [Muscle.glutes], [Muscle.hamstrings]),
    ("ex-143", "Hip Abduction Machine", "Glutes", "Machine", false, false,
     [Muscle.glutes, Muscle.abductors], []),
    ("ex-144", "Single-Leg Glute Bridge", "Glutes", "Bodyweight", false, true,
     [Muscle.glutes], [Muscle.hamstrings]),
    ("ex-18", "Calf Raise", "Calves", "Machine", false, false,
     [Muscle.gastrocnemius, Muscle.soleus], []),
    ("ex-105", "Seated Calf Raise", "Calves", "Machine", false, false,
     [Muscle.soleus], []),
    ("ex-106", "Donkey Calf Raise", "Calves", "Machine", false, false,
     [Muscle.gastrocnemius], []),
    ("ex-107", "Leg Press Calf Raise", "Calves", "Machine", false, false,
     [Muscle.gastrocnemius, Muscle.soleus], []),
    ("ex-20", "Crunches", "Core", "Bodyweight", false, false,
     [Muscle.abs], []),
    ("ex-15", "Plank", "Core", "Bodyweight", true, false,
     [Muscle.abs, Muscle.transverseAbdominis], [Muscle.obliques, Muscle.frontDelts]),
    ("ex-117", "Russian Twist", "Core", "Dumbbell", false, false,
     [Muscle.obliques, Muscle.abs], [Muscle.hipFlexors]),
    ("ex-118", "Leg Raise", "Core", "Bodyweight", false, false,
     [Muscle.abs, Muscle.hipFlexors], []),
    ("ex-119", "Woodchopper", "Core", "Cable", false, true,
     [Muscle.obliques, Muscle.abs], [Muscle.frontDelts]),
    ("ex-120", "Pallof Press", "Core", "Cable", false, true,
     [Muscle.obliques, Muscle.transverseAbdominis], [Muscle.abs]),
    ("ex-121", "Bird Dog", "Core", "Bodyweight", false, true,
     [Muscle.lowerBack, Muscle.abs], [Muscle.glutes, Muscle.frontDelts]),
    ("ex-122", "Dead Bug", "Core", "Bodyweight", false, false,
     [Muscle.abs, Muscle.transverseAbdominis], []),
    ("ex-123", "Cable Crunch", "Core", "Cable", false, false,
     [Muscle.abs], []),
    ("ex-124", "Ab Wheel Rollout", "Core", "Reps Only", false, false,
     [Muscle.abs, Muscle.lats], [Muscle.transverseAbdominis, Muscle.triceps]),
    ("ex-125", "Flutter Kick", "Core", "Bodyweight", true, false,
     [Muscle.abs, Muscle.hipFlexors], []),
    ("ex-126", "V-Up", "Core", "Bodyweight", false, false,
     [Muscle.abs, Muscle.hipFlexors], []),
    ("ex-127", "Side Bend", "Core", "Dumbbell", false, true,
     [Muscle.obliques], [Muscle.forearms]),
    ("ex-128", "Vacuum", "Core", "Bodyweight", true, false,
     [Muscle.transverseAbdominis], []),
    ("ex-156", "Hanging Leg Raise", "Core", "Assisted Bodyweight", false, false,
     [Muscle.abs, Muscle.hipFlexors], [Muscle.forearms, Muscle.lats, Muscle.wristFlexors]),
    ("ex-157", "Side Plank", "Core", "Bodyweight", true, true,
     [Muscle.obliques], [Muscle.abs, Muscle.sideDelts]),
    ("ex-159", "Push-up and Rotation", "Core", "Bodyweight", false, false,
     [Muscle.obliques, Muscle.abs], [Muscle.pectorals, Muscle.frontDelts]),
    ("ex-19", "Running", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem], [Muscle.quads, Muscle.hamstrings, Muscle.calves]),
    ("ex-115", "Cycling (Stationary)", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.quads], [Muscle.calves]),
    ("ex-129", "Jumping Jacks", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem], [Muscle.calves, Muscle.sideDelts]),
    ("ex-131", "Mountain Climber", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.abs], [Muscle.frontDelts, Muscle.hipFlexors]),
    ("ex-135", "Jump Rope", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.calves], []),
    ("ex-136", "Stair Climber", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.glutes, Muscle.quads], [Muscle.calves]),
    ("ex-158", "High Knees", "Cardio", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.hipFlexors], [Muscle.calves]),
    ("ex-130", "Burpee", "Full Body", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.pectorals, Muscle.quads], [Muscle.frontDelts, Muscle.abs]),
    ("ex-132", "Rowing (Machine)", "Full Body", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.lats], [Muscle.quads, Muscle.hamstrings, Muscle.biceps, Muscle.lowerBack]),
    ("ex-133", "Battle Rope", "Full Body", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.frontDelts], [Muscle.biceps, Muscle.triceps, Muscle.abs]),
    ("ex-134", "Kettlebell Swing", "Full Body", "Kettlebell", false, false,
     [Muscle.glutes, Muscle.hamstrings], [Muscle.lowerBack, Muscle.frontDelts, Muscle.forearms]),
    ("ex-137", "Swimming", "Full Body", "Cardio", true, false,
     [Muscle.cardiovascularSystem, Muscle.lats], [Muscle.frontDelts, Muscle.quads]),
    ("ex-145", "Turkish Get-Up", "Full Body", "Kettlebell", false, true,
     [Muscle.frontDelts, Muscle.abs], [Muscle.quads, Muscle.glutes, Muscle.triceps]),
    ("ex-146", "Kettlebell Clean & Press", "Full Body", "Kettlebell", false, true,
     [Muscle.frontDelts, Muscle.glutes, Muscle.hamstrings], [Muscle.triceps, Muscle.traps]),
    ("ex-147", "Kettlebell Snatch", "Full Body", "Kettlebell", false, true,
     [Muscle.glutes, Muscle.hamstrings, Muscle.frontDelts], [Muscle.lowerBack, Muscle.traps]),
    ("ex-149", "Medicine Ball Slam", "Full Body", "Reps Only", false, false,
     [Muscle.lats, Muscle.abs], [Muscle.triceps, Muscle.frontDelts]),
    ("ex-138", "Sun Salutation", "Mobility", "Bodyweight", true, false,
     [Muscle.cardiovascularSystem], []),
    ("ex-153", "Foam Rolling", "Mobility", "Bodyweight", true, true,
     [], []),
    ("ex-154", "Hip Flexor Stretch", "Mobility", "Bodyweight", true, true,
     [Muscle.hipFlexors], []),
    ("ex-155", "Cat-Cow Stretch", "Mobility", "Bodyweight", true, false,
     [Muscle.lowerBack], [Muscle.abs]),
]

/// Converts all seed exercise tuples to ExerciseM models for SwiftData seeding.
/// Populates instructions from the ExerciseInstructions database and localized names.
public func makeExerciseModels() -> [ExerciseM] {
    allSeedExercises.map { exercise in
        let id = exercise.0
        let name = exercise.1

        // Get instructions from the centralized database
        let instructionsArray = getExerciseInstructions(for: id) ?? []
        let instructionsJSON: String
        if !instructionsArray.isEmpty {
            // Encode as JSON string array for storage
            if let data = try? JSONEncoder().encode(instructionsArray),
               let jsonStr = String(data: data, encoding: .utf8) {
                instructionsJSON = jsonStr
            } else {
                instructionsJSON = ""
            }
        } else {
            instructionsJSON = ""
        }

        // Get localized name
        let localizedName = exerciseNamesES[id]

        return ExerciseM(
            id: id,
            name: name,
            bodyPart: exercise.2,
            category: exercise.3,
            isTimed: exercise.4,
            isUnilateral: exercise.5,
            primaryMuscles: exercise.6,
            secondaryMuscles: exercise.7,
            instructions: instructionsJSON,
            exerciseNamesEN: nil,
            exerciseNamesES: localizedName,
            difficulty: nil,
            updatedAt: Date(),
            deletedAt: nil
        )
    }
}

